on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Me"
      - run: echo "time ${{ steps.hello.outputs.time }}"
